-- ============================================================
-- Academy content batch 5 — finish Level 1 (Foundations) + Level 2 (Building Blocks) toward 100.
-- Buyer-facing fundamentals + process/disclosure mechanics. Dollar-quoted, per-row dedup.
-- ============================================================

insert into public.academy_items (kind, term, definition, note, level, sort, created_by_name)
select v.kind, v.term, v.definition, v.note, v.level, v.sort, v.created_by_name
from (values
  -- ── Level 1 — Foundations ──
  ('vocab', $$Interest rate$$, $$The percentage a lender charges to borrow, set when you lock.$$, null, 1, 200, $$Sal$$),
  ('vocab', $$Loan balance$$, $$The amount you still owe on the loan.$$, null, 1, 201, $$Sal$$),
  ('vocab', $$Buyer$$, $$The person purchasing the home.$$, null, 1, 202, $$Sal$$),
  ('vocab', $$Seller$$, $$The person selling the home.$$, null, 1, 203, $$Sal$$),
  ('vocab', $$Title company$$, $$Handles the title search, title insurance, and often the closing itself.$$, null, 1, 204, $$Sal$$),
  ('vocab', $$Closing attorney$$, $$In states like New York, the lawyer who handles the closing.$$, null, 1, 205, $$Sal$$),
  ('vocab', $$Settlement statement$$, $$The closing accounting of every cost — today's Closing Disclosure.$$, null, 1, 206, $$Sal$$),
  ('vocab', $$Listing agent$$, $$The agent who represents the seller.$$, null, 1, 207, $$Sal$$),
  ('vocab', $$Buyer's agent$$, $$The agent who represents the buyer.$$, null, 1, 208, $$Sal$$),
  ('vocab', $$Under contract$$, $$When the buyer and seller have a signed purchase agreement.$$, null, 1, 209, $$Sal$$),
  ('vocab', $$Contingent offer$$, $$An offer with conditions still to be satisfied before it's firm.$$, null, 1, 210, $$Sal$$),
  ('vocab', $$Final walkthrough$$, $$The buyer's last check of the home just before closing.$$, null, 1, 211, $$Sal$$),
  ('vocab', $$Possession$$, $$When the buyer gets the keys and takes the home.$$, null, 1, 212, $$Sal$$),
  ('vocab', $$Home inspection$$, $$A professional check of a home's condition before purchase.$$, null, 1, 213, $$Sal$$),
  ('vocab', $$Home warranty$$, $$A service contract covering home systems and appliances.$$, null, 1, 214, $$Sal$$),
  ('vocab', $$Appraisal fee$$, $$The cost to have the home professionally valued.$$, null, 1, 215, $$Sal$$),
  ('vocab', $$Application fee$$, $$An upfront fee some lenders charge to apply.$$, null, 1, 216, $$Sal$$),
  ('vocab', $$Hard inquiry$$, $$A credit pull for new credit that can slightly lower the score.$$, null, 1, 217, $$Sal$$),
  ('vocab', $$Soft inquiry$$, $$A credit check that doesn't affect the score.$$, null, 1, 218, $$Sal$$),
  ('vocab', $$Joint application$$, $$Applying for a loan together with another borrower.$$, null, 1, 219, $$Sal$$),
  ('vocab', $$Income$$, $$The money you earn, used to qualify for the loan.$$, null, 1, 220, $$Sal$$),
  ('vocab', $$Monthly debt$$, $$Your recurring monthly obligations, used in the DTI.$$, null, 1, 221, $$Sal$$),
  ('vocab', $$Assets$$, $$Money and property you own, like savings and retirement.$$, null, 1, 222, $$Sal$$),
  ('vocab', $$Liabilities$$, $$Your debts and financial obligations.$$, null, 1, 223, $$Sal$$),
  ('vocab', $$Net worth$$, $$Your assets minus your liabilities.$$, null, 1, 224, $$Sal$$),
  ('vocab', $$Bank statement$$, $$A monthly record of account activity that lenders review.$$, null, 1, 225, $$Sal$$),
  ('vocab', $$Tax return$$, $$Your filed IRS return, used to verify income.$$, null, 1, 226, $$Sal$$),
  ('vocab', $$W-2$$, $$A year-end wage statement from your employer.$$, null, 1, 227, $$Sal$$),
  ('vocab', $$Employment history$$, $$Your record of jobs, reviewed for stability.$$, null, 1, 228, $$Sal$$),
  ('vocab', $$Co-signer$$, $$Someone who guarantees the loan but may not be on title.$$, null, 1, 229, $$Sal$$),
  ('vocab', $$Loan program$$, $$The specific type and structure of a loan (FHA, conventional, etc.).$$, null, 1, 230, $$Sal$$),
  ('vocab', $$Government loan$$, $$A loan backed by FHA, VA, or USDA.$$, null, 1, 231, $$Sal$$),
  ('vocab', $$Conforming loan$$, $$A conventional loan within Fannie/Freddie size limits.$$, null, 1, 232, $$Sal$$),
  ('vocab', $$Interest-only$$, $$A payment option covering only interest for a set early period.$$, null, 1, 233, $$Sal$$),
  ('vocab', $$Prepayment$$, $$Paying extra toward principal to pay the loan off faster.$$, null, 1, 234, $$Sal$$),
  ('vocab', $$Affordability$$, $$How much home you can comfortably finance.$$, null, 1, 235, $$Sal$$),
  ('vocab', $$Housing payment$$, $$Your total monthly cost — principal, interest, taxes, and insurance.$$, null, 1, 236, $$Sal$$),
  ('vocab', $$Realtor$$, $$A licensed agent who belongs to the National Association of Realtors.$$, null, 1, 237, $$Sal$$),
  ('vocab', $$Loan denial$$, $$When a mortgage application isn't approved.$$, null, 1, 238, $$Sal$$),
  ('vocab', $$Fixer-upper$$, $$A home that needs repairs or updating.$$, null, 1, 239, $$Sal$$),
  ('vocab', $$As-is sale$$, $$A sale where the seller won't make repairs.$$, null, 1, 240, $$Sal$$),
  ('vocab', $$Open house$$, $$A scheduled time for buyers to tour a listed home.$$, null, 1, 241, $$Sal$$),
  ('vocab', $$Mortgage statement$$, $$The monthly statement showing your balance, payment, and escrow.$$, null, 1, 242, $$Sal$$),
  ('acronym', $$MLS$$, $$Multiple Listing Service$$, $$The shared database agents use to list and find homes for sale.$$, 1, 243, $$Sal$$),
  -- ── Level 2 — Building Blocks ──
  ('vocab', $$Three-day rule$$, $$The Closing Disclosure must be received 3 business days before closing.$$, null, 2, 250, $$Sal$$),
  ('vocab', $$Six pieces of an application$$, $$Name, income, SSN, address, value, loan amount — together they trigger disclosures.$$, null, 2, 251, $$Sal$$),
  ('vocab', $$Fee tolerance$$, $$How much a fee can rise from LE to CD — 0%, 10%, or unlimited buckets.$$, null, 2, 252, $$Sal$$),
  ('vocab', $$Zero-tolerance fees$$, $$Fees that can't increase at all, like lender charges and transfer taxes.$$, null, 2, 253, $$Sal$$),
  ('vocab', $$Finance charge$$, $$The total dollar cost of credit over the life of the loan.$$, null, 2, 254, $$Sal$$),
  ('vocab', $$Amount financed$$, $$The loan amount minus prepaid finance charges.$$, null, 2, 255, $$Sal$$),
  ('vocab', $$Origination points$$, $$Points charged to originate the loan, separate from discount points.$$, null, 2, 256, $$Sal$$),
  ('vocab', $$Aggregate adjustment$$, $$An escrow accounting credit at setup so the lender doesn't over-collect.$$, null, 2, 257, $$Sal$$),
  ('vocab', $$Escrow cushion$$, $$The extra one-to-two months of escrow a lender is allowed to hold.$$, null, 2, 258, $$Sal$$),
  ('vocab', $$Initial escrow deposit$$, $$The upfront money that funds the escrow account at closing.$$, null, 2, 259, $$Sal$$),
  ('vocab', $$Insurance binder$$, $$Temporary proof of homeowners insurance required at closing.$$, null, 2, 260, $$Sal$$),
  ('vocab', $$Mortgagee clause$$, $$The lender's info that must appear on the insurance policy.$$, null, 2, 261, $$Sal$$),
  ('vocab', $$Declarations page$$, $$The summary page of an insurance policy listing coverage and the mortgagee.$$, null, 2, 262, $$Sal$$),
  ('vocab', $$Replacement cost$$, $$The dwelling coverage amount insurers and lenders require.$$, null, 2, 263, $$Sal$$),
  ('vocab', $$Approve/Eligible$$, $$A DU result meaning the loan meets guidelines for automated approval.$$, null, 2, 264, $$Sal$$),
  ('vocab', $$Refer/Eligible$$, $$A DU result that's eligible but needs a manual underwrite.$$, null, 2, 265, $$Sal$$),
  ('vocab', $$Qualifying rate$$, $$The rate used to qualify a borrower — for an ARM, often higher than the start rate.$$, null, 2, 266, $$Sal$$),
  ('vocab', $$Liquid assets$$, $$Funds easily converted to cash for closing and reserves.$$, null, 2, 267, $$Sal$$),
  ('vocab', $$Sourced funds$$, $$Money traced to an acceptable, documented origin.$$, null, 2, 268, $$Sal$$),
  ('vocab', $$Seasoned funds$$, $$Money in the account long enough (usually 60 days) to count without sourcing.$$, null, 2, 269, $$Sal$$),
  ('vocab', $$Down payment sourcing$$, $$Documenting where the down-payment money came from.$$, null, 2, 270, $$Sal$$),
  ('vocab', $$Occupancy affidavit$$, $$A signed statement of how the borrower will occupy the home.$$, null, 2, 271, $$Sal$$),
  ('vocab', $$First payment date$$, $$When the first mortgage payment is due after closing.$$, null, 2, 272, $$Sal$$),
  ('vocab', $$Grace period$$, $$The days after the due date before a late fee applies.$$, null, 2, 273, $$Sal$$),
  ('vocab', $$Late fee$$, $$A charge for paying after the grace period ends.$$, null, 2, 274, $$Sal$$),
  ('vocab', $$Escrow refund$$, $$Money returned to you when the escrow account is overfunded.$$, null, 2, 275, $$Sal$$),
  ('vocab', $$Escrow disbursement$$, $$When the servicer pays your taxes and insurance from escrow.$$, null, 2, 276, $$Sal$$),
  ('vocab', $$Tax proration$$, $$Splitting property taxes between buyer and seller at closing.$$, null, 2, 277, $$Sal$$),
  ('vocab', $$Wire instructions$$, $$Where closing funds are sent — verify directly, a top fraud target.$$, null, 2, 278, $$Sal$$),
  ('vocab', $$Wire fraud$$, $$A scam that redirects closing funds with fake instructions — always call to confirm.$$, null, 2, 279, $$Sal$$),
  ('vocab', $$Loan modification$$, $$Changing the terms of an existing loan, often for hardship.$$, null, 2, 280, $$Sal$$),
  ('vocab', $$Biweekly payments$$, $$Paying half the mortgage every two weeks to pay down faster.$$, null, 2, 281, $$Sal$$),
  ('vocab', $$Suspense$$, $$A file paused by underwriting for missing information.$$, null, 2, 282, $$Sal$$),
  ('acronym', $$TIP$$, $$Total Interest Percentage$$, $$Total interest paid over the loan's life as a percent of the amount borrowed.$$, 2, 283, $$Sal$$),
  ('acronym', $$HCLTV$$, $$Home-Equity Combined Loan-to-Value$$, $$Like CLTV but counts the full credit line of a HELOC.$$, 2, 284, $$Sal$$),
  ('acronym', $$CPL$$, $$Closing Protection Letter$$, $$The title insurer's protection for the lender against closing-agent error or fraud.$$, 2, 285, $$Sal$$)
) as v(kind, term, definition, note, level, sort, created_by_name)
where not exists (select 1 from public.academy_items a where a.term = v.term);
